### ISSUE TITLE
bug: release 2.1.0 is broken

### ISSUE THREAD

**Issue by imranbarbhuiya** [binarytf/binarytf#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

release 2.1.0 don't have `lib` folder

### Steps To Reproduce

Just check the compiled folders in 2.1.0

### Expected behavior

It should contain the lib folder as it's present in src

**Comment by favna** [comment]
Fixed in 2.1.1, all classes and interfaces and such are now exported on top level.
